#!/bin/sh -e

export PATH="/usr/sbin:/usr/bin:/sbin:/bin"

# Get directory where this script is stored and build paths relative to it
BASEDIR=$(dirname $(readlink -f $0))
mkdir -p "$BASEDIR/tmp"
TMPDIR=$(mktemp -d --tmpdir="$BASEDIR/tmp")
TARGETSDIR="$BASEDIR/targets"
SRCDIR="$BASEDIR/.."
DISTDIR="$BASEDIR/dist"

# Create output directory in the temp directory
OUTDIR="$TMPDIR/output"
if ! test -d "$OUTDIR" ; then mkdir -p "$OUTDIR" ; fi

# Source the global dist script
source "$TARGETSDIR/dist"

# Iterate over targets
find "$TARGETSDIR" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | while read target ; do
    TDIR="$TARGETSDIR/$target"

    # Create build directory
    BUILDDIR="$TMPDIR/$target"
    if ! test -d "$BUILDDIR" ; then mkdir -p "$BUILDDIR" ; fi

    # Build the target
    cd "$BUILDDIR" && cmake -C "$TDIR/initial" "$SRCDIR" && make && cd -

    # Source the targets dist script
    source "$TDIR/dist"
done

# Determine SDK version from progskeet.h
SDKVERSION=$(sed -n -e 's/^#define PROGSKEET_VERSION "\([^"]*\)"$/\1/gp' "$SRCDIR/progskeet.h")

# Build distribution files
if ! test -d "$DISTDIR" ; then mkdir -p "$DISTDIR" ; fi

DISTNAME="progskeet-sdk-$SDKVERSION"
DISTFILE="$DISTDIR/$DISTNAME.tar.gz"

ln -s "$OUTDIR" "$TMPDIR/$DISTNAME"
tar -chvzf "$DISTFILE" -C "$TMPDIR" "$DISTNAME"
rm "$TMPDIR/$DISTNAME"

# Cleanup
rm -r "$TMPDIR"

# Success
exit 0
